export const dailyWords = [
  {
    day: 1,
    word: "graph",
    meaning: "A five-letter English word",
    difficulty: "medium",
  },
  {
    day: 2,
    word: "nymph",
    meaning: "A five-letter English word",
    difficulty: "hard",
  },
  {
    day: 3,
    word: "touch",
    meaning: "A five-letter English word",
    difficulty: "medium",
  },
  {
    day: 4,
    word: "brave",
    meaning: "A five-letter English word",
    difficulty: "easy",
  },
  {
    day: 5,
    word: "truth",
    meaning: "A five-letter English word",
    difficulty: "medium",
  },
  {
    day: 6,
    word: "axiom",
    meaning: "A five-letter English word",
    difficulty: "hard",
  },
  {
    day: 7,
    word: "vivid",
    meaning: "A five-letter English word",
    difficulty: "medium",
  },
  {
    day: 8,
    word: "quick",
    meaning: "A five-letter English word",
    difficulty: "medium",
  },
  {
    day: 9,
    word: "solve",
    meaning: "A five-letter English word",
    difficulty: "medium",
  },
  {
    day: 10,
    word: "clean",
    meaning: "A five-letter English word",
    difficulty: "easy",
  },
  {
    day: 11,
    word: "smart",
    meaning: "A five-letter English word",
    difficulty: "easy",
  },
  {
    day: 12,
    word: "blend",
    meaning: "A five-letter English word",
    difficulty: "medium",
  },
  {
    day: 13,
    word: "raise",
    meaning: "A five-letter English word",
    difficulty: "easy",
  },
  {
    day: 14,
    word: "wrath",
    meaning: "A five-letter English word",
    difficulty: "hard",
  },
  {
    day: 15,
    word: "mirth",
    meaning: "A five-letter English word",
    difficulty: "medium",
  },
  {
    day: 16,
    word: "reach",
    meaning: "A five-letter English word",
    difficulty: "easy",
  },
  {
    day: 17,
    word: "sound",
    meaning: "A five-letter English word",
    difficulty: "easy",
  },
  {
    day: 18,
    word: "logic",
    meaning: "A five-letter English word",
    difficulty: "medium",
  },
  {
    day: 19,
    word: "knock",
    meaning: "A five-letter English word",
    difficulty: "hard",
  },
  {
    day: 20,
    word: "trend",
    meaning: "A five-letter English word",
    difficulty: "medium",
  },
  {
    day: 21,
    word: "quick",
    meaning: "A five-letter English word",
    difficulty: "medium",
  },
  {
    day: 22,
    word: "fresh",
    meaning: "A five-letter English word",
    difficulty: "easy",
  },
  {
    day: 23,
    word: "honor",
    meaning: "A five-letter English word",
    difficulty: "medium",
  },
  {
    day: 24,
    word: "brave",
    meaning: "A five-letter English word",
    difficulty: "easy",
  },
  {
    day: 25,
    word: "smile",
    meaning: "A five-letter English word",
    difficulty: "easy",
  },
  {
    day: 26,
    word: "guess",
    meaning: "A five-letter English word",
    difficulty: "medium",
  },
  {
    day: 27,
    word: "taste",
    meaning: "A five-letter English word",
    difficulty: "medium",
  },
  {
    day: 28,
    word: "sight",
    meaning: "A five-letter English word",
    difficulty: "medium",
  },
  {
    day: 29,
    word: "sense",
    meaning: "A five-letter English word",
    difficulty: "easy",
  },
  {
    day: 30,
    word: "array",
    meaning: "A five-letter English word",
    difficulty: "medium",
  },
  {
    day: 31,
    word: "laugh",
    meaning: "A five-letter English word",
    difficulty: "easy",
  },
  {
    day: 32,
    word: "grace",
    meaning: "A five-letter English word",
    difficulty: "easy",
  },
  {
    day: 33,
    word: "jolly",
    meaning: "A five-letter English word",
    difficulty: "hard",
  },
  {
    day: 34,
    word: "happy",
    meaning: "A five-letter English word",
    difficulty: "easy",
  },
  {
    day: 35,
    word: "adapt",
    meaning: "A five-letter English word",
    difficulty: "easy",
  },
  {
    day: 36,
    word: "alert",
    meaning: "A five-letter English word",
    difficulty: "easy",
  },
  {
    day: 37,
    word: "train",
    meaning: "A five-letter English word",
    difficulty: "medium",
  },
  {
    day: 38,
    word: "match",
    meaning: "A five-letter English word",
    difficulty: "medium",
  },
  {
    day: 39,
    word: "solve",
    meaning: "A five-letter English word",
    difficulty: "medium",
  },
  {
    day: 40,
    word: "honor",
    meaning: "A five-letter English word",
    difficulty: "medium",
  },
  {
    day: 41,
    word: "guess",
    meaning: "A five-letter English word",
    difficulty: "medium",
  },
  {
    day: 42,
    word: "worth",
    meaning: "A five-letter English word",
    difficulty: "medium",
  },
  {
    day: 43,
    word: "guess",
    meaning: "A five-letter English word",
    difficulty: "medium",
  },
  {
    day: 44,
    word: "stand",
    meaning: "A five-letter English word",
    difficulty: "easy",
  },
  {
    day: 45,
    word: "solid",
    meaning: "A five-letter English word",
    difficulty: "easy",
  },
  {
    day: 46,
    word: "fjord",
    meaning: "A five-letter English word",
    difficulty: "hard",
  },
  {
    day: 47,
    word: "vivid",
    meaning: "A five-letter English word",
    difficulty: "medium",
  },
  {
    day: 48,
    word: "index",
    meaning: "A five-letter English word",
    difficulty: "medium",
  },
  {
    day: 49,
    word: "quiet",
    meaning: "A five-letter English word",
    difficulty: "medium",
  },
  {
    day: 50,
    word: "guess",
    meaning: "A five-letter English word",
    difficulty: "medium",
  },
  {
    day: 51,
    word: "zesty",
    meaning: "A five-letter English word",
    difficulty: "hard",
  },
  {
    day: 52,
    word: "laugh",
    meaning: "A five-letter English word",
    difficulty: "easy",
  },
  {
    day: 53,
    word: "flame",
    meaning: "A five-letter English word",
    difficulty: "medium",
  },
  {
    day: 54,
    word: "blend",
    meaning: "A five-letter English word",
    difficulty: "medium",
  },
  {
    day: 55,
    word: "teach",
    meaning: "A five-letter English word",
    difficulty: "easy",
  },
  {
    day: 56,
    word: "think",
    meaning: "A five-letter English word",
    difficulty: "medium",
  },
  {
    day: 57,
    word: "array",
    meaning: "A five-letter English word",
    difficulty: "medium",
  },
  {
    day: 58,
    word: "trust",
    meaning: "A five-letter English word",
    difficulty: "easy",
  },
  {
    day: 59,
    word: "trend",
    meaning: "A five-letter English word",
    difficulty: "medium",
  },
  {
    day: 60,
    word: "power",
    meaning: "A five-letter English word",
    difficulty: "medium",
  },
  {
    day: 61,
    word: "quiet",
    meaning: "A five-letter English word",
    difficulty: "medium",
  },
  {
    day: 62,
    word: "flame",
    meaning: "A five-letter English word",
    difficulty: "medium",
  },
  {
    day: 63,
    word: "proud",
    meaning: "A five-letter English word",
    difficulty: "easy",
  },
  {
    day: 64,
    word: "nymph",
    meaning: "A five-letter English word",
    difficulty: "hard",
  },
  {
    day: 65,
    word: "glyph",
    meaning: "A five-letter English word",
    difficulty: "hard",
  },
  {
    day: 66,
    word: "skill",
    meaning: "A five-letter English word",
    difficulty: "medium",
  },
  {
    day: 67,
    word: "value",
    meaning: "A five-letter English word",
    difficulty: "medium",
  },
  {
    day: 68,
    word: "touch",
    meaning: "A five-letter English word",
    difficulty: "medium",
  },
  {
    day: 69,
    word: "blend",
    meaning: "A five-letter English word",
    difficulty: "medium",
  },
  {
    day: 70,
    word: "xenon",
    meaning: "A five-letter English word",
    difficulty: "hard",
  },
  {
    day: 71,
    word: "wrath",
    meaning: "A five-letter English word",
    difficulty: "hard",
  },
  {
    day: 72,
    word: "jazzy",
    meaning: "A five-letter English word",
    difficulty: "hard",
  },
  {
    day: 73,
    word: "taste",
    meaning: "A five-letter English word",
    difficulty: "medium",
  },
  {
    day: 74,
    word: "trend",
    meaning: "A five-letter English word",
    difficulty: "medium",
  },
  {
    day: 75,
    word: "charm",
    meaning: "A five-letter English word",
    difficulty: "easy",
  },
  {
    day: 76,
    word: "teach",
    meaning: "A five-letter English word",
    difficulty: "easy",
  },
  {
    day: 77,
    word: "eager",
    meaning: "A five-letter English word",
    difficulty: "medium",
  },
  {
    day: 78,
    word: "index",
    meaning: "A five-letter English word",
    difficulty: "medium",
  },
  {
    day: 79,
    word: "adapt",
    meaning: "A five-letter English word",
    difficulty: "easy",
  },
  {
    day: 80,
    word: "array",
    meaning: "A five-letter English word",
    difficulty: "medium",
  },
  {
    day: 81,
    word: "drive",
    meaning: "A five-letter English word",
    difficulty: "medium",
  },
  {
    day: 82,
    word: "power",
    meaning: "A five-letter English word",
    difficulty: "medium",
  },
  {
    day: 83,
    word: "clear",
    meaning: "A five-letter English word",
    difficulty: "easy",
  },
  {
    day: 84,
    word: "fresh",
    meaning: "A five-letter English word",
    difficulty: "easy",
  },
  {
    day: 85,
    word: "touch",
    meaning: "A five-letter English word",
    difficulty: "medium",
  },
  {
    day: 86,
    word: "clean",
    meaning: "A five-letter English word",
    difficulty: "easy",
  },
  {
    day: 87,
    word: "plaza",
    meaning: "A five-letter English word",
    difficulty: "hard",
  },
  {
    day: 88,
    word: "sound",
    meaning: "A five-letter English word",
    difficulty: "easy",
  },
  {
    day: 89,
    word: "fairy",
    meaning: "A five-letter English word",
    difficulty: "easy",
  },
  {
    day: 90,
    word: "quirk",
    meaning: "A five-letter English word",
    difficulty: "hard",
  },
  {
    day: 91,
    word: "smart",
    meaning: "A five-letter English word",
    difficulty: "easy",
  },
  {
    day: 92,
    word: "think",
    meaning: "A five-letter English word",
    difficulty: "medium",
  },
  {
    day: 93,
    word: "worth",
    meaning: "A five-letter English word",
    difficulty: "medium",
  },
  {
    day: 94,
    word: "jolly",
    meaning: "A five-letter English word",
    difficulty: "hard",
  },
  {
    day: 95,
    word: "crypt",
    meaning: "A five-letter English word",
    difficulty: "hard",
  },
  {
    day: 96,
    word: "solve",
    meaning: "A five-letter English word",
    difficulty: "medium",
  },
  {
    day: 97,
    word: "truth",
    meaning: "A five-letter English word",
    difficulty: "medium",
  },
  {
    day: 98,
    word: "vivid",
    meaning: "A five-letter English word",
    difficulty: "medium",
  },
  {
    day: 99,
    word: "drive",
    meaning: "A five-letter English word",
    difficulty: "medium",
  },
  {
    day: 100,
    word: "think",
    meaning: "A five-letter English word",
    difficulty: "medium",
  },
  {
    day: 101,
    word: "taste",
    meaning: "A five-letter English word",
    difficulty: "medium",
  },
  {
    day: 102,
    word: "sight",
    meaning: "A five-letter English word",
    difficulty: "medium",
  },
  {
    day: 103,
    word: "swift",
    meaning: "A five-letter English word",
    difficulty: "medium",
  },
  {
    day: 104,
    word: "kayak",
    meaning: "A five-letter English word",
    difficulty: "hard",
  },
  {
    day: 105,
    word: "judge",
    meaning: "A five-letter English word",
    difficulty: "medium",
  },
  {
    day: 106,
    word: "study",
    meaning: "A five-letter English word",
    difficulty: "easy",
  },
  {
    day: 107,
    word: "vigor",
    meaning: "A five-letter English word",
    difficulty: "hard",
  },
  {
    day: 108,
    word: "knock",
    meaning: "A five-letter English word",
    difficulty: "hard",
  },
  {
    day: 109,
    word: "match",
    meaning: "A five-letter English word",
    difficulty: "medium",
  },
  {
    day: 110,
    word: "mirth",
    meaning: "A five-letter English word",
    difficulty: "medium",
  },
  {
    day: 111,
    word: "truth",
    meaning: "A five-letter English word",
    difficulty: "medium",
  },
  {
    day: 112,
    word: "judge",
    meaning: "A five-letter English word",
    difficulty: "medium",
  },
  {
    day: 113,
    word: "array",
    meaning: "A five-letter English word",
    difficulty: "medium",
  },
  {
    day: 114,
    word: "array",
    meaning: "A five-letter English word",
    difficulty: "medium",
  },
  {
    day: 115,
    word: "index",
    meaning: "A five-letter English word",
    difficulty: "medium",
  },
  {
    day: 116,
    word: "model",
    meaning: "A five-letter English word",
    difficulty: "easy",
  },
  {
    day: 117,
    word: "axiom",
    meaning: "A five-letter English word",
    difficulty: "hard",
  },
  {
    day: 118,
    word: "blend",
    meaning: "A five-letter English word",
    difficulty: "medium",
  },
  {
    day: 119,
    word: "speak",
    meaning: "A five-letter English word",
    difficulty: "easy",
  },
  {
    day: 120,
    word: "loyal",
    meaning: "A five-letter English word",
    difficulty: "easy",
  },
  {
    day: 121,
    word: "index",
    meaning: "A five-letter English word",
    difficulty: "medium",
  },
  {
    day: 122,
    word: "value",
    meaning: "A five-letter English word",
    difficulty: "medium",
  },
  {
    day: 123,
    word: "train",
    meaning: "A five-letter English word",
    difficulty: "medium",
  },
  {
    day: 124,
    word: "watch",
    meaning: "A five-letter English word",
    difficulty: "easy",
  },
  {
    day: 125,
    word: "graph",
    meaning: "A five-letter English word",
    difficulty: "medium",
  },
  {
    day: 126,
    word: "fairy",
    meaning: "A five-letter English word",
    difficulty: "easy",
  },
  {
    day: 127,
    word: "faith",
    meaning: "A five-letter English word",
    difficulty: "easy",
  },
  {
    day: 128,
    word: "sight",
    meaning: "A five-letter English word",
    difficulty: "medium",
  },
  {
    day: 129,
    word: "drive",
    meaning: "A five-letter English word",
    difficulty: "medium",
  },
  {
    day: 130,
    word: "peace",
    meaning: "A five-letter English word",
    difficulty: "easy",
  },
  {
    day: 131,
    word: "taste",
    meaning: "A five-letter English word",
    difficulty: "medium",
  },
  {
    day: 132,
    word: "crypt",
    meaning: "A five-letter English word",
    difficulty: "hard",
  },
  {
    day: 133,
    word: "fuzzy",
    meaning: "A five-letter English word",
    difficulty: "hard",
  },
  {
    day: 134,
    word: "swift",
    meaning: "A five-letter English word",
    difficulty: "medium",
  },
  {
    day: 135,
    word: "proxy",
    meaning: "A five-letter English word",
    difficulty: "hard",
  },
  {
    day: 136,
    word: "value",
    meaning: "A five-letter English word",
    difficulty: "medium",
  },
  {
    day: 137,
    word: "mirth",
    meaning: "A five-letter English word",
    difficulty: "medium",
  },
  {
    day: 138,
    word: "logic",
    meaning: "A five-letter English word",
    difficulty: "medium",
  },
  {
    day: 139,
    word: "train",
    meaning: "A five-letter English word",
    difficulty: "medium",
  },
  {
    day: 140,
    word: "vigor",
    meaning: "A five-letter English word",
    difficulty: "hard",
  },
  {
    day: 141,
    word: "value",
    meaning: "A five-letter English word",
    difficulty: "medium",
  },
  {
    day: 142,
    word: "honor",
    meaning: "A five-letter English word",
    difficulty: "medium",
  },
  {
    day: 143,
    word: "logic",
    meaning: "A five-letter English word",
    difficulty: "medium",
  },
  {
    day: 144,
    word: "flame",
    meaning: "A five-letter English word",
    difficulty: "medium",
  },
  {
    day: 145,
    word: "trust",
    meaning: "A five-letter English word",
    difficulty: "easy",
  },
  {
    day: 146,
    word: "proud",
    meaning: "A five-letter English word",
    difficulty: "easy",
  },
  {
    day: 147,
    word: "quiet",
    meaning: "A five-letter English word",
    difficulty: "medium",
  },
  {
    day: 148,
    word: "think",
    meaning: "A five-letter English word",
    difficulty: "medium",
  },
  {
    day: 149,
    word: "match",
    meaning: "A five-letter English word",
    difficulty: "medium",
  },
  {
    day: 150,
    word: "truth",
    meaning: "A five-letter English word",
    difficulty: "medium",
  },
  {
    day: 151,
    word: "quick",
    meaning: "A five-letter English word",
    difficulty: "medium",
  },
  {
    day: 152,
    word: "blend",
    meaning: "A five-letter English word",
    difficulty: "medium",
  },
  {
    day: 153,
    word: "trend",
    meaning: "A five-letter English word",
    difficulty: "medium",
  },
  {
    day: 154,
    word: "think",
    meaning: "A five-letter English word",
    difficulty: "medium",
  },
  {
    day: 155,
    word: "solid",
    meaning: "A five-letter English word",
    difficulty: "easy",
  },
  {
    day: 156,
    word: "flame",
    meaning: "A five-letter English word",
    difficulty: "medium",
  },
  {
    day: 157,
    word: "match",
    meaning: "A five-letter English word",
    difficulty: "medium",
  },
  {
    day: 158,
    word: "quiet",
    meaning: "A five-letter English word",
    difficulty: "medium",
  },
  {
    day: 159,
    word: "trend",
    meaning: "A five-letter English word",
    difficulty: "medium",
  },
  {
    day: 160,
    word: "logic",
    meaning: "A five-letter English word",
    difficulty: "medium",
  },
  {
    day: 161,
    word: "judge",
    meaning: "A five-letter English word",
    difficulty: "medium",
  },
  {
    day: 162,
    word: "stone",
    meaning: "A five-letter English word",
    difficulty: "medium",
  },
  {
    day: 163,
    word: "ivory",
    meaning: "A five-letter English word",
    difficulty: "hard",
  },
  {
    day: 164,
    word: "jazzy",
    meaning: "A five-letter English word",
    difficulty: "hard",
  },
  {
    day: 165,
    word: "zonal",
    meaning: "A five-letter English word",
    difficulty: "hard",
  },
  {
    day: 166,
    word: "power",
    meaning: "A five-letter English word",
    difficulty: "medium",
  },
  {
    day: 167,
    word: "skill",
    meaning: "A five-letter English word",
    difficulty: "medium",
  },
  {
    day: 168,
    word: "train",
    meaning: "A five-letter English word",
    difficulty: "medium",
  },
  {
    day: 169,
    word: "skill",
    meaning: "A five-letter English word",
    difficulty: "medium",
  },
  {
    day: 170,
    word: "graph",
    meaning: "A five-letter English word",
    difficulty: "medium",
  },
  {
    day: 171,
    word: "equip",
    meaning: "A five-letter English word",
    difficulty: "hard",
  },
  {
    day: 172,
    word: "touch",
    meaning: "A five-letter English word",
    difficulty: "medium",
  },
  {
    day: 173,
    word: "match",
    meaning: "A five-letter English word",
    difficulty: "medium",
  },
  {
    day: 174,
    word: "alert",
    meaning: "A five-letter English word",
    difficulty: "easy",
  },
  {
    day: 175,
    word: "kayak",
    meaning: "A five-letter English word",
    difficulty: "hard",
  },
  {
    day: 176,
    word: "vivid",
    meaning: "A five-letter English word",
    difficulty: "medium",
  },
  {
    day: 177,
    word: "faith",
    meaning: "A five-letter English word",
    difficulty: "easy",
  },
  {
    day: 178,
    word: "honor",
    meaning: "A five-letter English word",
    difficulty: "medium",
  },
  {
    day: 179,
    word: "solve",
    meaning: "A five-letter English word",
    difficulty: "medium",
  },
  {
    day: 180,
    word: "eager",
    meaning: "A five-letter English word",
    difficulty: "medium",
  },
  {
    day: 181,
    word: "graph",
    meaning: "A five-letter English word",
    difficulty: "medium",
  },
  {
    day: 182,
    word: "prize",
    meaning: "A five-letter English word",
    difficulty: "easy",
  },
  {
    day: 183,
    word: "glyph",
    meaning: "A five-letter English word",
    difficulty: "hard",
  },
  {
    day: 184,
    word: "mirth",
    meaning: "A five-letter English word",
    difficulty: "medium",
  },
  {
    day: 185,
    word: "value",
    meaning: "A five-letter English word",
    difficulty: "medium",
  },
  {
    day: 186,
    word: "truth",
    meaning: "A five-letter English word",
    difficulty: "medium",
  },
  {
    day: 187,
    word: "index",
    meaning: "A five-letter English word",
    difficulty: "medium",
  },
  {
    day: 188,
    word: "clear",
    meaning: "A five-letter English word",
    difficulty: "easy",
  },
  {
    day: 189,
    word: "quirk",
    meaning: "A five-letter English word",
    difficulty: "hard",
  },
  {
    day: 190,
    word: "grace",
    meaning: "A five-letter English word",
    difficulty: "easy",
  },
  {
    day: 191,
    word: "taste",
    meaning: "A five-letter English word",
    difficulty: "medium",
  },
  {
    day: 192,
    word: "worth",
    meaning: "A five-letter English word",
    difficulty: "medium",
  },
  {
    day: 193,
    word: "prize",
    meaning: "A five-letter English word",
    difficulty: "easy",
  },
  {
    day: 194,
    word: "sight",
    meaning: "A five-letter English word",
    difficulty: "medium",
  },
  {
    day: 195,
    word: "raise",
    meaning: "A five-letter English word",
    difficulty: "easy",
  },
  {
    day: 196,
    word: "stone",
    meaning: "A five-letter English word",
    difficulty: "medium",
  },
  {
    day: 197,
    word: "graph",
    meaning: "A five-letter English word",
    difficulty: "medium",
  },
  {
    day: 198,
    word: "reach",
    meaning: "A five-letter English word",
    difficulty: "easy",
  },
  {
    day: 199,
    word: "swift",
    meaning: "A five-letter English word",
    difficulty: "medium",
  },
  {
    day: 200,
    word: "power",
    meaning: "A five-letter English word",
    difficulty: "medium",
  },
  {
    day: 201,
    word: "sight",
    meaning: "A five-letter English word",
    difficulty: "medium",
  },
  {
    day: 202,
    word: "drive",
    meaning: "A five-letter English word",
    difficulty: "medium",
  },
  {
    day: 203,
    word: "quiet",
    meaning: "A five-letter English word",
    difficulty: "medium",
  },
  {
    day: 204,
    word: "happy",
    meaning: "A five-letter English word",
    difficulty: "easy",
  },
  {
    day: 205,
    word: "stone",
    meaning: "A five-letter English word",
    difficulty: "medium",
  },
  {
    day: 206,
    word: "speak",
    meaning: "A five-letter English word",
    difficulty: "easy",
  },
  {
    day: 207,
    word: "drive",
    meaning: "A five-letter English word",
    difficulty: "medium",
  },
  {
    day: 208,
    word: "swift",
    meaning: "A five-letter English word",
    difficulty: "medium",
  },
  {
    day: 209,
    word: "solve",
    meaning: "A five-letter English word",
    difficulty: "medium",
  },
  {
    day: 210,
    word: "loyal",
    meaning: "A five-letter English word",
    difficulty: "easy",
  },
  {
    day: 211,
    word: "quick",
    meaning: "A five-letter English word",
    difficulty: "medium",
  },
  {
    day: 212,
    word: "charm",
    meaning: "A five-letter English word",
    difficulty: "easy",
  },
  {
    day: 213,
    word: "skill",
    meaning: "A five-letter English word",
    difficulty: "medium",
  },
  {
    day: 214,
    word: "proxy",
    meaning: "A five-letter English word",
    difficulty: "hard",
  },
  {
    day: 215,
    word: "fuzzy",
    meaning: "A five-letter English word",
    difficulty: "hard",
  },
  {
    day: 216,
    word: "worth",
    meaning: "A five-letter English word",
    difficulty: "medium",
  },
  {
    day: 217,
    word: "flame",
    meaning: "A five-letter English word",
    difficulty: "medium",
  },
  {
    day: 218,
    word: "skill",
    meaning: "A five-letter English word",
    difficulty: "medium",
  },
  {
    day: 219,
    word: "vivid",
    meaning: "A five-letter English word",
    difficulty: "medium",
  },
  {
    day: 220,
    word: "power",
    meaning: "A five-letter English word",
    difficulty: "medium",
  },
  {
    day: 221,
    word: "quick",
    meaning: "A five-letter English word",
    difficulty: "medium",
  },
  {
    day: 222,
    word: "model",
    meaning: "A five-letter English word",
    difficulty: "easy",
  },
  {
    day: 223,
    word: "honor",
    meaning: "A five-letter English word",
    difficulty: "medium",
  },
  {
    day: 224,
    word: "judge",
    meaning: "A five-letter English word",
    difficulty: "medium",
  },
  {
    day: 225,
    word: "guess",
    meaning: "A five-letter English word",
    difficulty: "medium",
  },
  {
    day: 226,
    word: "judge",
    meaning: "A five-letter English word",
    difficulty: "medium",
  },
  {
    day: 227,
    word: "touch",
    meaning: "A five-letter English word",
    difficulty: "medium",
  },
  {
    day: 228,
    word: "stand",
    meaning: "A five-letter English word",
    difficulty: "easy",
  },
  {
    day: 229,
    word: "watch",
    meaning: "A five-letter English word",
    difficulty: "easy",
  },
  {
    day: 230,
    word: "ivory",
    meaning: "A five-letter English word",
    difficulty: "hard",
  },
  {
    day: 231,
    word: "zesty",
    meaning: "A five-letter English word",
    difficulty: "hard",
  },
  {
    day: 232,
    word: "worth",
    meaning: "A five-letter English word",
    difficulty: "medium",
  },
  {
    day: 233,
    word: "plaza",
    meaning: "A five-letter English word",
    difficulty: "hard",
  },
  {
    day: 234,
    word: "fjord",
    meaning: "A five-letter English word",
    difficulty: "hard",
  },
  {
    day: 235,
    word: "peace",
    meaning: "A five-letter English word",
    difficulty: "easy",
  },
  {
    day: 236,
    word: "sense",
    meaning: "A five-letter English word",
    difficulty: "easy",
  },
  {
    day: 237,
    word: "eager",
    meaning: "A five-letter English word",
    difficulty: "medium",
  },
  {
    day: 238,
    word: "logic",
    meaning: "A five-letter English word",
    difficulty: "medium",
  },
  {
    day: 239,
    word: "equip",
    meaning: "A five-letter English word",
    difficulty: "hard",
  },
  {
    day: 240,
    word: "xenon",
    meaning: "A five-letter English word",
    difficulty: "hard",
  },
  {
    day: 241,
    word: "eager",
    meaning: "A five-letter English word",
    difficulty: "medium",
  },
  {
    day: 242,
    word: "smile",
    meaning: "A five-letter English word",
    difficulty: "easy",
  },
  {
    day: 243,
    word: "zonal",
    meaning: "A five-letter English word",
    difficulty: "hard",
  },
  {
    day: 244,
    word: "study",
    meaning: "A five-letter English word",
    difficulty: "easy",
  },
  {
    day: 245,
    word: "swift",
    meaning: "A five-letter English word",
    difficulty: "medium",
  },
  {
    day: 246,
    word: "stone",
    meaning: "A five-letter English word",
    difficulty: "medium",
  },
  {
    day: 247,
    word: "stone",
    meaning: "A five-letter English word",
    difficulty: "medium",
  },
  {
    day: 248,
    word: "train",
    meaning: "A five-letter English word",
    difficulty: "medium",
  },
  {
    day: 249,
    word: "mirth",
    meaning: "A five-letter English word",
    difficulty: "medium",
  },
  {
    day: 250,
    word: "eager",
    meaning: "A five-letter English word",
    difficulty: "medium",
  },
  {
    day: 251,
    word: "graph",
    meaning: "A five-letter English word",
    difficulty: "medium",
  },
  {
    day: 252,
    word: "nymph",
    meaning: "A five-letter English word",
    difficulty: "hard",
  },
  {
    day: 253,
    word: "touch",
    meaning: "A five-letter English word",
    difficulty: "medium",
  },
  {
    day: 254,
    word: "brave",
    meaning: "A five-letter English word",
    difficulty: "easy",
  },
  {
    day: 255,
    word: "truth",
    meaning: "A five-letter English word",
    difficulty: "medium",
  },
  {
    day: 256,
    word: "axiom",
    meaning: "A five-letter English word",
    difficulty: "hard",
  },
  {
    day: 257,
    word: "vivid",
    meaning: "A five-letter English word",
    difficulty: "medium",
  },
  {
    day: 258,
    word: "quick",
    meaning: "A five-letter English word",
    difficulty: "medium",
  },
  {
    day: 259,
    word: "solve",
    meaning: "A five-letter English word",
    difficulty: "medium",
  },
  {
    day: 260,
    word: "clean",
    meaning: "A five-letter English word",
    difficulty: "easy",
  },
  {
    day: 261,
    word: "smart",
    meaning: "A five-letter English word",
    difficulty: "easy",
  },
  {
    day: 262,
    word: "blend",
    meaning: "A five-letter English word",
    difficulty: "medium",
  },
  {
    day: 263,
    word: "raise",
    meaning: "A five-letter English word",
    difficulty: "easy",
  },
  {
    day: 264,
    word: "wrath",
    meaning: "A five-letter English word",
    difficulty: "hard",
  },
  {
    day: 265,
    word: "mirth",
    meaning: "A five-letter English word",
    difficulty: "medium",
  },
  {
    day: 266,
    word: "reach",
    meaning: "A five-letter English word",
    difficulty: "easy",
  },
  {
    day: 267,
    word: "sound",
    meaning: "A five-letter English word",
    difficulty: "easy",
  },
  {
    day: 268,
    word: "logic",
    meaning: "A five-letter English word",
    difficulty: "medium",
  },
  {
    day: 269,
    word: "knock",
    meaning: "A five-letter English word",
    difficulty: "hard",
  },
  {
    day: 270,
    word: "trend",
    meaning: "A five-letter English word",
    difficulty: "medium",
  },
  {
    day: 271,
    word: "quick",
    meaning: "A five-letter English word",
    difficulty: "medium",
  },
  {
    day: 272,
    word: "fresh",
    meaning: "A five-letter English word",
    difficulty: "easy",
  },
  {
    day: 273,
    word: "honor",
    meaning: "A five-letter English word",
    difficulty: "medium",
  },
  {
    day: 274,
    word: "brave",
    meaning: "A five-letter English word",
    difficulty: "easy",
  },
  {
    day: 275,
    word: "smile",
    meaning: "A five-letter English word",
    difficulty: "easy",
  },
  {
    day: 276,
    word: "guess",
    meaning: "A five-letter English word",
    difficulty: "medium",
  },
  {
    day: 277,
    word: "taste",
    meaning: "A five-letter English word",
    difficulty: "medium",
  },
  {
    day: 278,
    word: "sight",
    meaning: "A five-letter English word",
    difficulty: "medium",
  },
  {
    day: 279,
    word: "sense",
    meaning: "A five-letter English word",
    difficulty: "easy",
  },
  {
    day: 280,
    word: "array",
    meaning: "A five-letter English word",
    difficulty: "medium",
  },
  {
    day: 281,
    word: "laugh",
    meaning: "A five-letter English word",
    difficulty: "easy",
  },
  {
    day: 282,
    word: "grace",
    meaning: "A five-letter English word",
    difficulty: "easy",
  },
  {
    day: 283,
    word: "jolly",
    meaning: "A five-letter English word",
    difficulty: "hard",
  },
  {
    day: 284,
    word: "happy",
    meaning: "A five-letter English word",
    difficulty: "easy",
  },
  {
    day: 285,
    word: "adapt",
    meaning: "A five-letter English word",
    difficulty: "easy",
  },
  {
    day: 286,
    word: "alert",
    meaning: "A five-letter English word",
    difficulty: "easy",
  },
  {
    day: 287,
    word: "train",
    meaning: "A five-letter English word",
    difficulty: "medium",
  },
  {
    day: 288,
    word: "match",
    meaning: "A five-letter English word",
    difficulty: "medium",
  },
  {
    day: 289,
    word: "solve",
    meaning: "A five-letter English word",
    difficulty: "medium",
  },
  {
    day: 290,
    word: "honor",
    meaning: "A five-letter English word",
    difficulty: "medium",
  },
  {
    day: 291,
    word: "guess",
    meaning: "A five-letter English word",
    difficulty: "medium",
  },
  {
    day: 292,
    word: "worth",
    meaning: "A five-letter English word",
    difficulty: "medium",
  },
  {
    day: 293,
    word: "guess",
    meaning: "A five-letter English word",
    difficulty: "medium",
  },
  {
    day: 294,
    word: "stand",
    meaning: "A five-letter English word",
    difficulty: "easy",
  },
  {
    day: 295,
    word: "solid",
    meaning: "A five-letter English word",
    difficulty: "easy",
  },
  {
    day: 296,
    word: "fjord",
    meaning: "A five-letter English word",
    difficulty: "hard",
  },
  {
    day: 297,
    word: "vivid",
    meaning: "A five-letter English word",
    difficulty: "medium",
  },
  {
    day: 298,
    word: "index",
    meaning: "A five-letter English word",
    difficulty: "medium",
  },
  {
    day: 299,
    word: "quiet",
    meaning: "A five-letter English word",
    difficulty: "medium",
  },
  {
    day: 300,
    word: "guess",
    meaning: "A five-letter English word",
    difficulty: "medium",
  },
  {
    day: 301,
    word: "zesty",
    meaning: "A five-letter English word",
    difficulty: "hard",
  },
  {
    day: 302,
    word: "laugh",
    meaning: "A five-letter English word",
    difficulty: "easy",
  },
  {
    day: 303,
    word: "flame",
    meaning: "A five-letter English word",
    difficulty: "medium",
  },
  {
    day: 304,
    word: "blend",
    meaning: "A five-letter English word",
    difficulty: "medium",
  },
  {
    day: 305,
    word: "teach",
    meaning: "A five-letter English word",
    difficulty: "easy",
  },
  {
    day: 306,
    word: "think",
    meaning: "A five-letter English word",
    difficulty: "medium",
  },
  {
    day: 307,
    word: "array",
    meaning: "A five-letter English word",
    difficulty: "medium",
  },
  {
    day: 308,
    word: "trust",
    meaning: "A five-letter English word",
    difficulty: "easy",
  },
  {
    day: 309,
    word: "trend",
    meaning: "A five-letter English word",
    difficulty: "medium",
  },
  {
    day: 310,
    word: "power",
    meaning: "A five-letter English word",
    difficulty: "medium",
  },
  {
    day: 311,
    word: "quiet",
    meaning: "A five-letter English word",
    difficulty: "medium",
  },
  {
    day: 312,
    word: "flame",
    meaning: "A five-letter English word",
    difficulty: "medium",
  },
  {
    day: 313,
    word: "proud",
    meaning: "A five-letter English word",
    difficulty: "easy",
  },
  {
    day: 314,
    word: "nymph",
    meaning: "A five-letter English word",
    difficulty: "hard",
  },
  {
    day: 315,
    word: "glyph",
    meaning: "A five-letter English word",
    difficulty: "hard",
  },
  {
    day: 316,
    word: "skill",
    meaning: "A five-letter English word",
    difficulty: "medium",
  },
  {
    day: 317,
    word: "value",
    meaning: "A five-letter English word",
    difficulty: "medium",
  },
  {
    day: 318,
    word: "touch",
    meaning: "A five-letter English word",
    difficulty: "medium",
  },
  {
    day: 319,
    word: "blend",
    meaning: "A five-letter English word",
    difficulty: "medium",
  },
  {
    day: 320,
    word: "xenon",
    meaning: "A five-letter English word",
    difficulty: "hard",
  },
  {
    day: 321,
    word: "wrath",
    meaning: "A five-letter English word",
    difficulty: "hard",
  },
  {
    day: 322,
    word: "jazzy",
    meaning: "A five-letter English word",
    difficulty: "hard",
  },
  {
    day: 323,
    word: "taste",
    meaning: "A five-letter English word",
    difficulty: "medium",
  },
  {
    day: 324,
    word: "trend",
    meaning: "A five-letter English word",
    difficulty: "medium",
  },
  {
    day: 325,
    word: "charm",
    meaning: "A five-letter English word",
    difficulty: "easy",
  },
  {
    day: 326,
    word: "teach",
    meaning: "A five-letter English word",
    difficulty: "easy",
  },
  {
    day: 327,
    word: "eager",
    meaning: "A five-letter English word",
    difficulty: "medium",
  },
  {
    day: 328,
    word: "index",
    meaning: "A five-letter English word",
    difficulty: "medium",
  },
  {
    day: 329,
    word: "adapt",
    meaning: "A five-letter English word",
    difficulty: "easy",
  },
  {
    day: 330,
    word: "array",
    meaning: "A five-letter English word",
    difficulty: "medium",
  },
  {
    day: 331,
    word: "drive",
    meaning: "A five-letter English word",
    difficulty: "medium",
  },
  {
    day: 332,
    word: "power",
    meaning: "A five-letter English word",
    difficulty: "medium",
  },
  {
    day: 333,
    word: "clear",
    meaning: "A five-letter English word",
    difficulty: "easy",
  },
  {
    day: 334,
    word: "fresh",
    meaning: "A five-letter English word",
    difficulty: "easy",
  },
  {
    day: 335,
    word: "touch",
    meaning: "A five-letter English word",
    difficulty: "medium",
  },
  {
    day: 336,
    word: "clean",
    meaning: "A five-letter English word",
    difficulty: "easy",
  },
  {
    day: 337,
    word: "plaza",
    meaning: "A five-letter English word",
    difficulty: "hard",
  },
  {
    day: 338,
    word: "sound",
    meaning: "A five-letter English word",
    difficulty: "easy",
  },
  {
    day: 339,
    word: "fairy",
    meaning: "A five-letter English word",
    difficulty: "easy",
  },
  {
    day: 340,
    word: "quirk",
    meaning: "A five-letter English word",
    difficulty: "hard",
  },
  {
    day: 341,
    word: "smart",
    meaning: "A five-letter English word",
    difficulty: "easy",
  },
  {
    day: 342,
    word: "think",
    meaning: "A five-letter English word",
    difficulty: "medium",
  },
  {
    day: 343,
    word: "worth",
    meaning: "A five-letter English word",
    difficulty: "medium",
  },
  {
    day: 344,
    word: "jolly",
    meaning: "A five-letter English word",
    difficulty: "hard",
  },
  {
    day: 345,
    word: "crypt",
    meaning: "A five-letter English word",
    difficulty: "hard",
  },
  {
    day: 346,
    word: "solve",
    meaning: "A five-letter English word",
    difficulty: "medium",
  },
  {
    day: 347,
    word: "truth",
    meaning: "A five-letter English word",
    difficulty: "medium",
  },
  {
    day: 348,
    word: "vivid",
    meaning: "A five-letter English word",
    difficulty: "medium",
  },
  {
    day: 349,
    word: "drive",
    meaning: "A five-letter English word",
    difficulty: "medium",
  },
  {
    day: 350,
    word: "think",
    meaning: "A five-letter English word",
    difficulty: "medium",
  },
  {
    day: 351,
    word: "taste",
    meaning: "A five-letter English word",
    difficulty: "medium",
  },
  {
    day: 352,
    word: "sight",
    meaning: "A five-letter English word",
    difficulty: "medium",
  },
  {
    day: 353,
    word: "swift",
    meaning: "A five-letter English word",
    difficulty: "medium",
  },
  {
    day: 354,
    word: "kayak",
    meaning: "A five-letter English word",
    difficulty: "hard",
  },
  {
    day: 355,
    word: "judge",
    meaning: "A five-letter English word",
    difficulty: "medium",
  },
  {
    day: 356,
    word: "study",
    meaning: "A five-letter English word",
    difficulty: "easy",
  },
  {
    day: 357,
    word: "vigor",
    meaning: "A five-letter English word",
    difficulty: "hard",
  },
  {
    day: 358,
    word: "knock",
    meaning: "A five-letter English word",
    difficulty: "hard",
  },
  {
    day: 359,
    word: "match",
    meaning: "A five-letter English word",
    difficulty: "medium",
  },
  {
    day: 360,
    word: "mirth",
    meaning: "A five-letter English word",
    difficulty: "medium",
  },
  {
    day: 361,
    word: "truth",
    meaning: "A five-letter English word",
    difficulty: "medium",
  },
  {
    day: 362,
    word: "judge",
    meaning: "A five-letter English word",
    difficulty: "medium",
  },
  {
    day: 363,
    word: "array",
    meaning: "A five-letter English word",
    difficulty: "medium",
  },
  {
    day: 364,
    word: "array",
    meaning: "A five-letter English word",
    difficulty: "medium",
  },
  {
    day: 365,
    word: "index",
    meaning: "A five-letter English word",
    difficulty: "medium",
  },
];
